### PR TITLE
Document `WNConfig`

### LINKED ISSUE #748: `WNConfig` lack of documentation
### Problem Description

X.L.WindowNavigation doesn't document how to use `WNConfig` or the functions it provides to create one.

### Steps to Reproduce

See https://xmonad.github.io/xmonad-docs/xmonad-contrib-0.17.0.9/XMonad-Layout-WindowNavigation.html.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.0.9 (commit 83a8bb8 if using git)
    - [x] With `xmonad-contrib` version 0.17.0.9 (commit 063d97f if using git)

### PR DESCRIPTION
**Pull request by geekosaur**
### Description

`configurableNavigation` in XMonad.Layout.WindowNavigation uses an opaque type `WNConfig` and provides three undocumented functions to create `WNConfig` values. Provide some documentation for them, so it at least makes some kind of sense.

Closes #748.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: doc change

  - [n/a] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by geekosaur** [comment]
Also document the default value.

**Comment by geekosaur** [comment]
Also, I'd just put this directly into `master` because it's just a doc change, but I still don't trust my Haddock markup skills.

File: XMonad/Layout/WindowNavigation.hs [hunk 1]
```diff
@@ -72,6 +72,14 @@ data Navigate = Go Direction2D | Swap Direction2D | Move Direction2D
               | Apply (Window -> X()) Direction2D -- ^ Apply action with destination window
 instance Message Navigate
 
+-- | Used with @configurableNavigation@ to specify how to show reachable windows'
```
Comment (slotThe) [inline XMonad/Layout/WindowNavigation.hs:75]: AFAIK, if we want to link to functions we have to use `'…'` instead of `@…@` (which is just monospace)

**Review by slotThe — APPROVED** [review]
LGTM, aside from the markup stuff (I didn't build it locally, so I may be off, but that's how I remember Haddock to work)

File: XMonad/Layout/WindowNavigation.hs (hunk 1 above)
Comment (geekosaur) [reply XMonad/Layout/WindowNavigation.hs:75]: That's what I thought, but the existing markup uses `@…@`. I'll fix that too.

Comment (geekosaur) [reply XMonad/Layout/WindowNavigation.hs:75]: That's what I thought, but the existing markup uses `@…@`. I'll fix that too.

**Comment by geekosaur** [comment]
Uh. @slotThe, this failed an OrgMode test for some reason? I didn't even touch that.

**Comment by slotThe** [comment]
Lol.  Consider it unrelated, I will take a look at the X.P.OrgMode tests tomorrow

**Comment by slotThe** [comment]
@geekosaur should be fixed by c701a75002bf7f089732a59c23360153d1178e1c
